### PR TITLE
Add MNIST dataset

### PR DESCRIPTION
**Pull request by chimame**
### Overview
Corresponds to MNIST dataset

### Changes
- Add to_gdk_pixbuf method to record of MNIST
  - Generate RGB from pixel values ​​of MNIST
- Add test code

### CODE REVIEW

**Comment by chimame** [comment]
Does Ruby 2.2 support it?
[red-datasets](https://github.com/red-data-tools/red-datasets/blob/master/.travis.yml) seems to support 2.3 or higher.

**Comment by kou** [comment]
We can drop Ruby 2.2 support. Because it's EOL.

**Comment by kou** [comment]
Thanks!
Can you also add `example/mnist.rb` to confirm images with real data?

**Comment by chimame** [comment]
@kou Thanks
`example/mnist.rb` was added!

**Comment by kou** [comment]
Thanks! We can also support Fashion MNIST.

**Pull request merged**
